admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /
usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /
#eCloud
root:
    path:    /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /home
        permanent: true
home:
    path: /home
    defaults: { _controller: UsuarioBundle:Sitio:Home }

################################################################################################ USUARIOS
login:
    path: /login
    defaults: { _controller: UsuarioBundle:Security:login }
login_check:
    path: /login_check
logout:
    path: /logout
registro:
    path: /registro
    defaults: { _controller: UsuarioBundle:Registro:registro}
recovery:
    path: /recovery
    defaults: { _controller: UsuarioBundle:Security:recovery}

#PERFILES, PROTEGIDO BAJO FIREWALL
perfil:
    path: /perfil
    defaults: { _controller: UsuarioBundle:Cuenta:perfil }
ficheros:
    path: /ficheros
    defaults: { _controller: UsuarioBundle:Cuenta:ficheros, ruta: / }
_ficheros:
    path: /ficheros/
    defaults: { _controller: UsuarioBundle:Cuenta:ficheros, ruta: / }
ficheros2:
    path: /ficheros/{ruta}
    defaults: { _controller: UsuarioBundle:Cuenta:ficheros, ruta: / }
    requirements:
        ruta: ".+"
_ficheros2:
    path: /ficheros/{ruta}/
    defaults: { _controller: UsuarioBundle:Cuenta:ficheros, ruta: / }
    requirements:
        ruta: ".+"
fichero:
    path: /fichero/{id}
    defaults: { _controller: UsuarioBundle:Cuenta:fichero, id: 0 }
    requirements:
        id:  \d+
subir:
    path: /subir
    defaults: { _controller: UsuarioBundle:Cuenta:subir }
modificar:
    path: /modificar/{fichero}
    defaults: { _controller: UsuarioBundle:Cuenta:modificar, fichero: 0 }
    requirements:
        fichero:  \d+
borrar:
    path: /borrar/{fichero}
    defaults: { _controller: UsuarioBundle:Cuenta:borrar }
    requirements:
        fichero:  \d+
descargar:
    path: /descargar/{fichero}
    defaults: { _controller: UsuarioBundle:Cuenta:descargar }
eventos:
    path: /eventos
    defaults: { _controller: UsuarioBundle:Cuenta:eventos }
links:
    path: /links
    defaults: { _controller: UsuarioBundle:Cuenta:links, id: 0 }
borrarlink:
    path: /borrarlink/{id}
    defaults: { _controller: UsuarioBundle:Cuenta:borrarlink, id: 0 }
################################################################################################ API
api_conectado:
    path: /api/conectado
    defaults: { _controller: UsuarioBundle:Cuenta:conectado }
api_perfil:
    path: /api/perfil/{info}
    defaults: { _controller: UsuarioBundle:Cuenta:perfiljson, info: all }
api_ficheros:
    path: /api/ficheros
    defaults: { _controller: UsuarioBundle:Cuenta:ficherosjson, ruta: / }
_api_ficheros:
    path: /api/ficheros/
    defaults: { _controller: UsuarioBundle:Cuenta:ficherosjson, ruta: / }
api_ficheros2:
    path: /api/ficheros/{ruta}
    defaults: { _controller: UsuarioBundle:Cuenta:ficherosjson, ruta: / }
    requirements:
        ruta: ".+"
api_modificar:
    path: /api/modificar/{fichero}
    defaults: { _controller: UsuarioBundle:Cuenta:modificarjson, fichero: 0 }
    requirements:
        fichero:  \d+
api_fichero:
    path: /api/fichero/{id}
    defaults: { _controller: UsuarioBundle:Cuenta:ficherojson, id: 0 }
api_eventos:
    path: /api/eventos/desde={desde}&hasta={hasta}&start={start}&cantidad={cantidad}&nocache={nocache}
    defaults: { _controller: UsuarioBundle:Cuenta:eventosjson, desde: 1, hasta: 1, start: 0, cantidad: 100000}
    requirements:
        desde: "^(([0-2]\d|[3][0-1])\-([0]\d|[1][0-2])\-[2][0]\d{2})$"
        hasta: "^(([0-2]\d|[3][0-1])\-([0]\d|[1][0-2])\-[2][0]\d{2})$"
        start: "^[0-9]{1,6}"
        cantidad: "^[0-9]{1,6}"
################################################################################################ Descarga Externa
download:
    path: /!{descarga}
    defaults: { _controller: UsuarioBundle:Cuenta:download, descarga: 0 }
############################################################################################## SECCION ADMIN
admin_home:
    path: /admin
    defaults: { _controller: AdminBundle:Admin:home }
_admin_home:
    path: /admin/
    defaults: { _controller: AdminBundle:Admin:home }
admin_usuarios:
    path: /admin/usuarios/{id}
    defaults: { _controller: AdminBundle:Admin:usuarios, id: 0 }
admin_usuarios_modificar:
    path: /admin/usuarios/modificar/{id}
    defaults: { _controller: AdminBundle:Admin:modificarusuarios, id: 0 }
admin_usuarios_borrar:
    path: /admin/usuarios/borrar/{id}
    defaults: { _controller: AdminBundle:Admin:borrarusuarios }
admin_stats:
    path: /admin/stats
    defaults: { _controller: AdminBundle:Admin:stats }
admin_login:
    path: /admin/login
    defaults: { _controller: AdminBundle:AdminSecurity:login }
admin_login_check:
    path: /admin/login_check
admin_logout:
    path: /admin/logout

################################################################################################ PAGINAS ESTATICAS FRONTEND AL FINAL, YA QUE ES CUANDO LAS OTRAS NO LAS ENCUENTRA
ayuda:
    path: /ayuda
    defaults: { _controller: UsuarioBundle:Sitio:ayuda }
contacto:
    path: /contacto
    defaults: { _controller: UsuarioBundle:Sitio:contacto }
privacidad:
    path: /privacidad
    defaults: { _controller: UsuarioBundle:Sitio:privacidad }
sobre-nosotros:
    path: /sobre-nosotros
    defaults: { _controller: UsuarioBundle:Sitio:sobrenosotros }
#No encontrado -> Home
Noencontrado:
    path: /{pagina}
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /home
        permanent: true
    requirements:
        pagina: .+