admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /
usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /
#eCloud
root:
    path:    /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /home
        permanent: true
home:
    pattern: /home
    defaults: { _controller: UsuarioBundle:Sitio:Home }

################################################################################################MANEJO DE USUARIOS
login:
    pattern: /login
    defaults: { _controller: UsuarioBundle:Security:login }
login_check:
    pattern: /login_check
logout:
    pattern: /logout
registro:
    path: /registro
    defaults: { _controller: UsuarioBundle:Registro:Registro}

#PERFILES, PROTEGIDO BAJO FIREWALL
perfil:
    pattern: /perfil
    defaults: { _controller: UsuarioBundle:Cuenta:perfil }
ficheros:
    pattern: /ficheros
    defaults: { _controller: UsuarioBundle:Cuenta:ficheros, ruta: / }
_ficheros:
    pattern: /ficheros/
    defaults: { _controller: UsuarioBundle:Cuenta:ficheros, ruta: / }
ficheros2:
    pattern: /ficheros/{ruta}
    defaults: { _controller: UsuarioBundle:Cuenta:ficheros, ruta: / }
    requirements:
        ruta: ".+"
_ficheros2:
    pattern: /ficheros/{ruta}/
    defaults: { _controller: UsuarioBundle:Cuenta:ficheros, ruta: / }
    requirements:
        ruta: ".+"
subir:
    pattern: /subir
    defaults: { _controller: UsuarioBundle:Cuenta:subir }
modificar:
    pattern: /modificar/{fichero}
    defaults: { _controller: UsuarioBundle:Cuenta:modificar }
borrar:
    pattern: /borrar/{fichero}
    defaults: { _controller: UsuarioBundle:Cuenta:borrar }
descargar:
    pattern: /descargar/{fichero}
    defaults: { _controller: UsuarioBundle:Cuenta:descargar }
eventos:
    pattern: /eventos
    defaults: { _controller: UsuarioBundle:Cuenta:eventos }
links:
    pattern: /links
    defaults: { _controller: UsuarioBundle:Cuenta:links }

############################################################################################## SECCION ADMIN
admin_home:
    pattern: /admin
    defaults: { _controller: AdminBundle:Admin:home }
admin_usuarios:
    pattern: /admin/usuarios
    defaults: { _controller: AdminBundle:Admin:usuarios }
admin_stats:
    pattern: /admin/stats
    defaults: { _controller: AdminBundle:Admin:stats }
admin_login:
    pattern: /admin/login
    defaults: { _controller: AdminBundle:Security:login }
admin_login_check:
    pattern: /admin/login_check
logout:
    pattern: /admin/logout

################################################################################################PAGINAS ESTATICAS FRONTEND AL FINAL, YA QUE ES CUANDO LAS OTRAS NO LAS ENCUENTRA
ayuda:
    pattern: /ayuda
    defaults: { _controller: UsuarioBundle:Sitio:ayuda }
contacto:
    pattern: /contacto
    defaults: { _controller: UsuarioBundle:Sitio:contacto }
privacidad:
    pattern: /privacidad
    defaults: { _controller: UsuarioBundle:Sitio:privacidad }
sobre-nosotros:
    pattern: /sobre-nosotros
    defaults: { _controller: UsuarioBundle:Sitio:sobrenosotros }

#No encontrado -> Home
Noencontrado:
    pattern: /{pagina}
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /home
        permanent: true