jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        eCloud\UsuarioBundle\Entity\Usuarios: { algorithm: sha512, iterations:0, encode_as_base64: false }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users:
            entity: { class: eCloud\UsuarioBundle\Entity\Usuarios, property: email }
            #user:  { password: userpass, roles: [ 'ROLE_USER' ] }
            #admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /home
                always_use_default_target_path: true
            logout:
                path:   /logout
            #    target: _demo
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
        admin_area:
            pattern:    ^/admin
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
                default_target_path: /admin/home
                always_use_default_target_path: true
            logout:
                path:   /admin/logout
            #    target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }